### Creates a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name" : "John Doe Kafka Test",
  "email": "kafka_test@email.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-12",
  "registeredDate": "2025-03-20"
}

###